
const systemIcons = [
  // 疑问
  'question',
  'question-circle',
  'question-circle-o',
  // 暂停
  'pause',
  'pause-circle',
  'pause-circle-o',
  // info
  'info',
  'info-circle',
  'info-circle-o',
  // 感叹号 警告（三角形框）
  'warning',
  'warning-circle',
  'warning-circle-o',
  // 加减
  'plus',
  'plus-circle',
  'plus-circle-o',
  'plus-square',
  'plus-square-o',
  'minus',
  'minus-circle',
  'minus-circle-o',
  'minus-square',
  'minus-square-o',
  // 选择 正确 or 成功
  'check',
  'check-circle',
  'check-circle-o',
  'check-square',
  'check-square-o',
  // 关闭 错误 or 失败
  'cross',
  'cross-circle',
  'cross-circle-o',
  'cross-square',
  'cross-square-o',
  // clock
  'clock-circle',
  'clock-circle-o',
  // 其他常用 icon
  'loading',
]
const customIcons = [
  ['add', ''],
  ['arrow_alt', '层级'],
  ['inbox', '收件箱'],
  ['inbox_active', '收件箱'],
  ['duplicates', '重复的'],
  ['duplicates_active', ''],
  ['trash', '废纸篓'],
  ['trash_active', ''],

  ['title', ''],
  ['default_collection', ''],
  ['default_collection_active', ''],
  ['16_default_collection', ''],
  ['new_collection', '新的收藏集'],
  ['new_collection_active', ''],
  ['tag', '标签'],
  ['tag_active', ''],
  ['cloud', '全部'],
  ['cloud_active', ''],
  ['like', '最喜爱的'],
  ['like_active', '从最喜爱的删除'],
  ['like_outline', '添加到最喜爱的'],
  ['micro_tag', ''],
  ['micro_next', ''],
  ['micro_link', ''],
  ['micro_article', ''],
  ['micro_dropdown', ''],
  ['micro_important', ''],
  ['micro_video', ''],

  ['title', ''],
  ['check_active', '选择'],
  ['select_all', '选择所有'],
  ['upload', '上传照片'],
  ['upload_active', ''],
  ['close', ''],
  ['fonts', ''],
  ['search', ''],
  ['share', ''],
  ['arrow', ''],
  ['lock', ''],
  ['move_to', ''],

  ['title', ''],
  ['open', '在浏览器中打开'],
  ['more_horizontal', '右键点击书签或集合文件夹以获得更多功能'],
  ['view_simple', 'List'],
  ['view_list', 'Headlines'],
  ['view_grid', 'Cards'],
  ['view_gallery', 'Moodboard'],

  ['title', 'tabBar'],
  ['24_home', ''],
  ['24_home_active', ''],
  ['24_install', ''],
  ['24_install_active', ''],
  ['24_settings', ''],
  ['24_settings_active', ''],

  ['title', 'install/extension'],
  ['mobile', '移动应用'],
  ['extension', '浏览器扩展'],
  ['extension_active', ''],
  ['apple', 'macOS | iPhone & iPad'],
  ['apple_active', ''],
  ['microsoft', 'Windows'],
  ['microsoft_active', ''],
  ['android', 'Android'],
  ['android_active', ''],

  ['title', 'settings/upgrade'],
  ['diamond', '专业版账号'],
  ['diamond_active', ''],
  ['settings', '设置'],
  ['settings_active', ''],
  ['profile', '配置'],
  ['profile_active', ''],
  ['import', '导入书签'],
  ['import_active', ''],
  ['export', '导出书签'],
  ['export_active', ''],
  ['dropbox', 'Dropbox备份'],
  ['dropbox_active', ''],
  ['dev', '开发者支持'],
  ['tools', '为下一步要开发的新功能投票'],
  ['history', '帮助'],
  ['cloud', '关于我们'],
  ['cloud_active', ''],
  ['exit', '注销'],
  ['import_pocket', 'pocket'],
  ['import_instapaper', 'instapaper'],
  ['import_readability', 'readability'],

  ['title', '排序'],
  ['sort_lastUpdate', '按日期'],
  ['sort_lastUpdate_active', ''],
  ['sort_title', '按名称'],
  ['sort_title_active', ''],
  ['sort_rating', '按受欢迎程度'],
  ['sort_rating_active', ''],
  ['sort_domain', '网站'],
  ['sort_domain_active', ''],

  ['title', '编辑'],
  ['back', ''],
  ['fullscreen_active', ''],
  ['article', ''],
  ['article_active', ''],
  ['web', ''],
  ['web_active', ''],
  ['info', ''],
  ['info_active', ''],

  ['title', 'register/login'],
  ['email', ''],
  ['user', ''],
  ['lock', ''],
  ['keyword', ''],
  ['qq', ''],
  ['wechat', ''],
  ['github', ''],
]

export {
  systemIcons,
  customIcons,
}
