
export const components = [
  {
    title: '基础组件', // Layout
    list: [
      // {
      //   icon: '',
      //   path: 'blank',
      //   title: 'blank 间距留白',
      //   desc: '',
      //   status: 'doing',
      // },
      {
        icon: '',
        path: 'layout',
        title: 'layout 布局排版',
        desc: '',
        status: 'doing',
      },
      {
        icon: '',
        path: 'flex',
        title: 'flex 弹性布局',
        desc: '',
        status: 'doing',
      },
      {
        icon: '',
        path: 'grid',
        title: 'grid 栅格布局',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'button',
        title: 'button 按钮',
        desc: '',
        status: 'done',
      },
      {
        icon: '',
        path: 'icon',
        title: 'icon 图标',
        desc: '',
        status: 'done',
      },
      {
        icon: '',
        path: 'badge',
        title: 'badge 徽标',
        desc: '',
        status: 'done',
      },
      // {
      //   icon: '',
      //   path: 'tag',
      //   title: 'tag 标签',
      //   desc: '',
      //   status: 'todo',
      // },
      {
        icon: '',
        path: 'card',
        title: 'card 卡片',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'panel',
        title: 'panel 面板',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'cell',
        title: 'cell 单元格',
        desc: '',
        status: 'doing',
      },
      {
        icon: '',
        path: 'divider',
        title: 'divider 分割线',
        desc: '',
        status: 'done',
      },
      {
        icon: '',
        path: 'image-preview',
        title: 'ImagePreview 图片预览',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'lazyload',
        title: 'lazyload 图片懒加载',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'loading',
        title: 'loading 加载指示器',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'spin',
        title: 'spin 加载中',
        desc: '',
        status: 'done',
      },
      {
        icon: '',
        path: 'progress',
        title: 'progress 进度条',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'popup',
        title: 'popup 弹出层',
        desc: '从顶部或底部浮出的模态，提供标题和关闭按钮，展示和当前内容相关的信息或提供相关操作。',
        status: 'todo',
      },
      {
        icon: '',
        path: 'stepper',
        title: 'stepper 步进器',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'steps',
        title: 'steps 步骤条',
        desc: '',
        status: 'todo',
      },
    ],
  },
  {
    title: '导航', // Navigation
    list: [
      {
        icon: '',
        path: 'menu',
        title: 'menu 菜单',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'nav-bar',
        title: 'NavBar 导航条',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'tabs',
        title: 'tabs 标签页',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'tool-bar',
        title: 'ToolBar 工具条',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'search-bar',
        title: 'SearchBar 搜索栏',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'notice-bar',
        title: 'notice-bar 通告栏',
        desc: '',
        status: 'done',
      },
      {
        icon: '',
        path: 'drawer',
        title: 'drawer 侧边栏',
        desc: '',
        status: 'todo',
      },
    ],
  },
  {
    title: '表单及扩展', // FormExtend
    list: [
      {
        icon: '',
        path: 'switch',
        title: 'switch 滑动开关',
        desc: '在两个互斥对象进行选择，eg：选择开或关。',
        status: 'done',
      },
      {
        icon: '',
        path: 'input-item',
        title: 'InputField 表单输入',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'textarea-item',
        title: 'TextareaItem 多行输入',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'radio',
        title: 'radio 单选',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'checkbox',
        title: 'checkbox 多选',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'picker',
        title: 'Picker 选择器',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'date-picker',
        title: 'DatePicker 日期选择',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'image-picker',
        title: 'ImagePicker 图片选择',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'uploader',
        title: 'uploader 上传',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'custom-keyboard',
        title: 'custom-keyboard 自定义键盘',
        desc: '如数字键盘、身份证键盘、密码键盘（排序打乱）等',
        status: 'todo',
      },
      {
        icon: '',
        path: 'passwrad-input',
        title: 'passwrad-input 密码输入框',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'input-number',
        title: 'input-number 数字输入框',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'slider',
        title: 'Slider 滑动输入条',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'range',
        title: 'Range 区域选择',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'cascader',
        title: 'cascader 级联选择',
        desc: '',
        status: 'todo',
      },
    ],
  },
  {
    title: '操作反馈', // Feedback
    list: [
      {
        icon: '',
        path: 'toast',
        title: 'Toast 轻提示',
        desc: '一种轻量级反馈/提示，可以用来显示不会打断用户操作的内容，适合用于页面转场、数据交互的等场景中。',
        status: 'todo',
      },
      {
        icon: '',
        path: 'modal',
        title: 'Modal 对话框',
        desc: '用作显示系统的重要信息，并请求用户进行操作反馈，eg：删除某个重要内容时，弹出 Modal 进行二次确认。',
        status: 'todo',
      },
      {
        icon: '',
        path: 'pull-refresh',
        title: 'PullRefresh 下拉刷新',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'action-sheet',
        title: 'ActionSheet 操作表/动作面板',
        desc: '从底部浮出的模态，提供和当前场景相关的 2 个以上操作或者更多描述内容。',
        status: 'todo',
      },
      {
        icon: '',
        path: 'alert',
        title: 'alert 警告提示',
        desc: '警告提示，展现需要关注的信息。',
        status: 'done',
      },
      // {
      //   icon: '',
      //   path: 'popover',
      //   title: 'popover 气泡卡片',
      //   desc: '在点击控件或者某个区域后，浮出一个气泡区域来放置更多的操作或者信息。',
      //   status: 'todo',
      // },
      // {
      //   icon: '',
      //   path: 'tooltip',
      //   title: 'tooltip 文字提示',
      //   desc: '',
      //   status: 'todo',
      // },

      // {
      //   icon: '',
      //   path: 'spin',
      //   title: 'Spin 加载中',
      //   desc: '用于页面和区块的加载中状态。',
      //   status: 'doing',
      // },
      // {
      //   icon: '',
      //   path: 'confirm',
      //   title: 'confirm 确认框',
      //   desc: '',
      //   status: 'todo',
      // },
    ],
  },
  {
    title: '高阶组合', // Complex
    list: [
      {
        icon: '',
        path: 'tree-select',
        title: 'TreeSelect 树形选择',
        desc: '类似 Select 的选择控件，可选择的数据结构是一个树形结构时，可以使用 TreeSelect，例如公司层级、学科系统、分类目录等等。',
        status: 'todo',
      },
      {
        icon: '',
        path: 'tree',
        title: 'Tree 树形控件',
        desc: '文件夹、组织架构、生物分类、国家地区等等都是树形结构。使用树控件可以完整展现其中的层级关系，并具有展开收起选择等交互功能。',
        status: 'todo',
      },
      {
        icon: '',
        path: 'list-view',
        title: 'ListView 长列表',
        desc: '',
        status: 'todo',
      },
    ],
  },
  {
    title: '业务组件', // Combination
    list: [
      {
        icon: '',
        path: 'result',
        title: 'result 结果页',
        desc: '在整张页面中组织插画、图标、文字等内容，向用户反馈操作结果，eg：支付成功，无网络状态，重新加载。',
        status: 'todo',
      },
      {
        icon: '',
        path: 'area',
        title: 'area 省市区选择',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'address-list',
        title: 'addressList 地址列表',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'address-edit',
        title: 'addressEdit 地址编辑',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'contact',
        title: 'contact 联系人',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'coupon',
        title: 'coupon 优惠券选择器',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'goods-action',
        title: 'goodsAction 商品操作栏',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'submit-bar',
        title: 'submitBar 提交订单栏',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'sku',
        title: 'sku 商品规格弹层',
        desc: '',
        status: 'todo',
      },
      // {
      //   icon: '',
      //   path: 'index-list',
      //   title: 'index-list 索引列表', // 如联系人
      //   desc: '',
      //   status: 'todo',
      // },
      // {
      //   icon: '',
      //   path: 'media-list',
      //   title: 'media list 媒体列表',
      //   desc: '',
      //   status: 'todo',
      // },
    ],
  },
  // {
  //   title: 'Gesture 手势',
  //   list: [
  //     {
  //       icon: '',
  //       path: 'swipe-action',
  //       title: 'SwipeAction 滑动操作',
  //       desc: '',
  //       status: 'todo',
  //     },
  //     {
  //       icon: '',
  //       path: 'refresh-control',
  //       title: 'RefreshControl 下拉刷新',
  //       desc: '',
  //       status: 'todo',
  //     },
  //   ],
  // },
  {
    title: '其他',
    list: [
      {
        icon: '',
        path: 'anchor',
        title: 'Anchor 锚点',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'back-top',
        title: 'BackTop 回到顶部',
        desc: '',
        status: 'todo',
      },
      {
        icon: '',
        path: 'locale',
        title: 'Locale 国际化',
        desc: '为组件内建文案提供统一的国际化支持。',
        status: 'todo',
      },
    ],
  },
]

export const language = {
  'zh-cn': {
    home: '/',
    guideline: '/guideline',
    component: '/component',
    pattern: '/pattern',
    weapp: '/weapp',
  },
}
export default {
  header: {
    '首页': '/',
    '指引': '/guideline',
    '组件': '/component',
    // '模式': '/patterns',
    '实战': '/project',
    '小程序': '/weapp',
  },
  footer: {
    github: 'https://github.com/webcoding/vue-custom',
    nav: {
      '加入我们': 'https://devnode.cn/',
      '意见反馈': 'https://github.com/webcoding/vue-custom/issues',
    },
  },
  navBase: '/component',
  nav: [
    {
      title: '开发指南',
      groups: [
        {
          title: '',
          list: [
            {
              path: 'quickstart',
              title: '快速上手',
              status: 'doing',
            },
            {
              path: 'practical-projects',
              title: '项目实战',
              status: 'doing',
            },
            {
              path: 'customize-theme',
              title: '定制主题',
              status: 'todo',
            },
            {
              path: 'i18n',
              title: '国际化',
              status: 'todo',
            },
            {
              path: 'changelog',
              title: '更新日志',
              status: 'done',
            },
          ],
        },
      ],
    },
    {
      title: '组件',
      groups: components,
    },
  ],
}
